/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * <p>
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * <p>
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 *
 * Solution: 4613732
 */
public class Problem2 {

    public static void main(String[] args) {

        int previous = 1;
        int current = 2;
        int next;

        int total = current;

        System.out.println(previous);
        System.out.println(current);

        while ((next = previous + current) < 4 * 1000 * 1000) {
            System.out.println(next);

            if (next % 2 == 0)
                total += next;

            previous = current;
            current = next;
        }

        System.out.println("Sum: " + total);
    }
}
